# Database Configuration (Assuming local on M1 Max or RDS, configure via ENV vars)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=validate

# Storage Strategy (AWS S3)
app.storage.type=s3
app.storage.aws.bucket=hexmanos-assets-324037297014
app.storage.aws.prefix=live
aws.region=eu-central-1

# Cognito OAuth2 Configuration
app.cognito.player.issuer-uri=https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_PKYxYlFq6
app.cognito.admin.issuer-uri=https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_6vEHad3r7
